### ISSUE TITLE
Add checking if answer is downvoted

### ISSUE THREAD

**Issue by ricconoel** [ricconoel/so_metrics#3]
Add logic on tables to detect if answer is downvoted or not. Apply this on the summary view as well.

**Comment by ricconoel** [comment]
As per offline conversation with @anjelab04, changes will be done on the following:

1. Add `is_downvoted` field in **filtered_answer_YYYY_MM** view
2. In **calc_answer_YYYY_MM** add `is_downvoted` 
   - Logic: is_downvoted = true if 1 or more case of a user is downvoted
3. Add `is_downvoted` in **calc_summary_YYYYMM** view

**Comment by anjelab04** [comment]
> As per offline conversation with @anjelab04, changes will be done on the following:
> 
> 1. Add `is_downvoted` field in **filtered_answer_YYYY_MM** view - DONE
> 2. In **calc_answer_YYYY_MM** add `is_downvoted` - DONE
>    
>    * Logic: is_downvoted = true if 1 or more answer of a user is downvoted
> 3. Add `is_downvoted` in **calc_summary_YYYYMM** view - DONE

**Comment by anjelab04** [comment]
![summary_diff_202211](https://user-images.githubusercontent.com/97658366/202764692-8bd1176e-3c50-4e73-a714-d3b077d89d46.png)
![filtered_diff_202211](https://user-images.githubusercontent.com/97658366/202764706-9806668c-4fb3-46c4-b277-52d59baaca68.png)
![answer_diff_202211](https://user-images.githubusercontent.com/97658366/202764708-90452c96-aa37-4f4f-a66f-a552d86d8473.png)

**Comment by anjelab04** [comment]
validation using vimdiff done between prod and dev answer_view, filtered_view and summary_view for the month of November 2022

**Comment by anjelab04** [comment]
![summary_diff_202211](https://user-images.githubusercontent.com/97658366/202769345-7bca252b-7836-4f16-96c4-1f0c01b60ce7.png)
![filtered_diff_202211](https://user-images.githubusercontent.com/97658366/202769354-584dc32d-8d8f-4d5c-beb7-e20e6f9def50.png)
![answer_diff_202211](https://user-images.githubusercontent.com/97658366/202769357-5892df03-eaa5-42ba-aa6a-a57b1228e9d3.png)

**Comment by ricconoel** [comment]
Kindly take note of the following steps to release the changes in production:

1. Merge pull request
2. In your terminal, change branch to main (`git checkout main`) and update the main branch (git pull)
3. Delete the following views (tiph-ricconoel-batch8.so_dataset.calc_answer_202211, tiph-ricconoel-batch8.so_dataset.filtered_answer_202211,tiph-ricconoel-batch8.so_dataset.calc_summary_202211)
4. Run `python main.py` to update the views. (make sure you are on the main branch)
5. Check data if changes were applied

**Comment by anjelab04** [comment]
![upd_summary_diff_202211](https://user-images.githubusercontent.com/97658366/202783728-3b0b6f22-5121-43e6-9d98-308270aec11e.png)
![upd_filtered_diff_202211](https://user-images.githubusercontent.com/97658366/202783733-4a62aa73-0f90-4dd9-9029-78a067bac7c7.png)
![upd_answer_diff_202211](https://user-images.githubusercontent.com/97658366/202783734-626503ef-5dd0-45cb-8b5f-29f7cffd65f2.png)

**Comment by anjelab04** [comment]
Validation through vimdiff done for prod and dev summary, filtered and answered views using November 2022 data - both prod and dev are synchronized
