### ISSUE TITLE
Create summary of weekly stats

### ISSUE THREAD

**Issue by ricconoel** [ricconoel/so_metrics#9]
Create a view/s to get weekly and monthly summary for stats. Something similar like this:

![image](https://user-images.githubusercontent.com/80935916/201166585-0a35bd95-32cc-47a9-acb7-873ee1fd3722.png)

**Comment by jhoneterence** [comment]
test

**Comment by ricconoel** [comment]
Looking into this.

**Comment by ricconoel** [comment]
Encountered an issue when counting total cases when creating a weekly summary. This scenario describes the problem:

- remove duplicates is needed because of the following scenario:
  - post_week = 2022-10-30, comment_date = 2022-11-04, user_id = 111
    - comment on question A
    - This will count as total_case + 1
  - post_week = 2022-11-06, comment_date = 2022-11-07, user_id = 111
    - comment on question A
    - This will count as total_case + 1
- scenario above gives total_case = 2 for user_id = 111 since user commented on the same case on different weeks
- hence removing duplicates is needed
- will apply this workaround from SO https://stackoverflow.com/a/43865611/14733669

**Comment by ricconoel** [comment]
Hi @jhoneterence,

I was able to create the sample data for the weekly summary for both TSRs and program. Please see email for the link of the sample file.

**Comment by ricconoel** [comment]
Created a pull request and is currently for review.

**Comment by ricconoel** [comment]
Found a bug on the `sql_scripts/weekly_summary_view.sql` where it displays data that does not have a date but has a comment.

![image](https://user-images.githubusercontent.com/80935916/203402401-44cb11a3-0be1-4419-b0c5-ffa97146fc50.png)

This is caused by the joining logic of the view mentioned above. It joins in this manner:
```
full outer join `tiph-ricconoel-batch8.so_dataset_dev.test_calc_weekly_total_2022_11` t_total
  on t_total.user_id = coalesce(t_com.user_id,t_ans.user_id) and t_total.post_week = coalesce(t_com.week_date,t_ans.week_date)
```
`test_calc_weekly_total_2022_11` does not have data for the week of 2022-11-13 because of posting comments multiple times on a single question that crosses multiple weeks:

![image](https://user-images.githubusercontent.com/80935916/203406084-19e40a94-3c8c-41ba-bcf0-15e56f925e7a.png)

As seen in the image above, current logic only counts the questions that have `rn = 1` which is the latest comment on a question. 

This data is then joined with `test_calc_weekly_comment_2022_11`  where the comment is counted on a weekly basis. No checking of duplicates is done on this table. Hence when joining `total` and `weekly` a `null` value is shown.

Fix is to add `where total_cases is not null` in `sql_scripts/weekly_summary_view.sql`

**Comment by ricconoel** [comment]
Hi,

I updated the data in the test sheet named **test_data_2022_11**.

**Comment by ricconoel** [comment]
Hi,

As per offline conversation with @jhoneterence, weekly data looks good. A thing to add is creating a sheet that shows totals per month. Ex. Get total PAR, CWA, Total cases of the whole program per month.  Will be creating a separate issue for this.

**Comment by ricconoel** [comment]
Enhancement to add weekly summary for user and program is released to production
